# Generated by Django 4.2.16 on 2026-02-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'System Administrator'), ('MANAGER', 'Manager'), ('DISPATCHER', 'Dispatcher'), ('SAFETY', 'Safety Officer'), ('FINANCE', 'Finance')], default='DISPATCHER', max_length=20),
        ),
    ]
