# Generated by Django 4.2.16 on 2026-02-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_is_approved_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator (Boss)'), ('MANAGER', 'Fleet Manager'), ('DISPATCHER', 'Dispatcher'), ('SAFETY', 'Safety Officer'), ('FINANCE', 'Financial Analyst')], default='DISPATCHER', max_length=20),
        ),
    ]
