# Generated by Django 4.2.16 on 2026-02-21 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20, unique=True)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('vehicle_type', models.CharField(choices=[('VAN', 'Van'), ('TRUCK', 'Truck'), ('MINI', 'Mini')], default='VAN', max_length=10)),
                ('capacity_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('IN_SHOP', 'In Shop'), ('IDLE', 'Idle')], default='IDLE', max_length=10)),
                ('odometer', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
