# Generated by Django 4.2.16 on 2026-02-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='estimated_duration_mins',
            field=models.IntegerField(default=0),
        ),
    ]
